(AMCL) add resample limit cache
ros-planning/navigation pull request #1012
Opened 2020-07-16 18:41 UTC by MatthijsBurgh

This reduces the number of calculations significant as this function is called each time after adding a new sample during resampling.

2020-07-21 07:13 UTC, MatthijsBurgh commented
ping ;)

2020-07-24 19:36 UTC, DLu reviewed
I'm not familiar with the internals of amcl as well as I should be. Can you give a bit of context? How often is `pf_resample_limit` called with the same values? Is there ever a scenario where the cache could be invalid?

2020-07-24 19:59 UTC, MatthijsBurgh commented
The cache should never be invalid. The size is depending on `max_particles`, the values inside the cache depend on `min_particles`, `max_particles`, `pop_z` and `pop_err`. These can be changed during a reconfigure callback, but in that case, the entire filter is deleted and created again, thus also the cache, so both size and values are "reset".

I can't give you a number for calling with the same value during one resampling, as that really depends on the cell size and how your particles are spread. But between multiple resampling steps there will be significant overlap of the input values.
By default, resampling happens every 2 sensor updates. So probably at 10 Hz, During each resampling, `pf_resample_limit` is called at least `min_particles` times (100 by default), so at least 1000 times per second.

2020-08-04 07:46 UTC, MatthijsBurgh commented
@DLu ping ;)

2020-08-16 18:02 UTC, MatthijsBurgh commented
@DLu ping ;)

2020-08-20 15:19 UTC, MatthijsBurgh commented
ping @aaronhoy @mikeferguson ;)

2020-08-20 18:09 UTC, mikeferguson requested changes
Ok, @MatthijsBurgh your persistence has paid off - I finally dragged out my copy of Probabilistic Robotics to review KLD resampling. This looks good - except for the three comments noted - rather than an assert (which will disappear when compiled in RELEASE), let's make sure that k < 1 returns reasonable values. Also, let's prevent memory corruption.

2020-08-20 18:09 UTC, mikeferguson commented on amcl/src/amcl/pf/pf.c
> +  assert(k > 0);
so, is this important, are there instances when someone would actually call with k <= 0? It will actually be removed from the Debian release (and, actually, for almost everyone since it is recommended to compile in RELEASE to avoid issues with runtime speed).

I'd prefer we avoid hard-to-debug memory issues here at runtime, and instead return pf->max_samples if k < 1, and then we know that all the lines below are OK. Although I would also suggest updating L525 below

2020-08-20 18:09 UTC, mikeferguson commented on amcl/src/amcl/pf/pf.c
>    if (k <= 1)
if we return pf->max_samples for k < 1 above, make this (k == 1) for clarity

2020-08-20 18:09 UTC, mikeferguson commented on amcl/src/amcl/pf/pf.c
> +  if (pf->limit_cache[k-1] > 0)
before we access limit_cache[k-1]  we really should validate that k <= max_samples to avoid memory corruption

2020-08-20 19:32 UTC, MatthijsBurgh commented
@mikeferguson I have implemented your requests. I also added the changes to the kinetic PR, #1013, and the noetic PR, #1014.

2020-08-21 00:46 UTC, merged