Change_map service to map_server [Rebase/Noetic]
ros-planning/navigation pull request #1029
Opened 2020-09-22 15:02 UTC by DLu

This is a redo of #461 for noetic, integrating changes that have been made in the last 4 years since the original PR. :roll_eyes: 

The CI will fail until the changes from https://github.com/ros/common_msgs/pull/152 are released, see https://github.com/ros/common_msgs/issues/167

The return codes from the service are not ideal (in that it only returns success or failure, not the more nuanced failure codes described in the service) but I was trying to keep close to @sloretz's original PR structure.

2020-09-22 15:38 UTC, mikeferguson requested changes

2020-09-22 15:38 UTC, mikeferguson commented on map_server/CMakeLists.txt
> +            roslib
this seems to only be in the Cmake/package.xml - where is it actually used/required?

2020-09-22 15:38 UTC, mikeferguson commented on map_server/src/main.cpp
> +    std::string frame_id_;
should really be more consistent in naming here - member variable should all have the trailing underscore_

2021-02-17 18:14 UTC, EricWiener commented
Any progress updates on this?

2021-03-02 01:50 UTC, DLu commented
@ros-pull-request-builder retest this please

2021-03-03 21:20 UTC, EricWiener commented
@DLu thanks for seeing if the tests pass. Does it look good to merge?

2021-03-04 20:49 UTC, DLu commented
I think so. Let's get the +1 from @mikeferguson first since he had formally reviewed it earlier.

2021-04-18 20:15 UTC, EricWiener commented
Any progress on this?

2021-04-19 13:12 UTC, mikeferguson approved these changes

2021-04-19 13:12 UTC, mikeferguson commented on map_server/src/main.cpp
> +      ROS_INFO("Changed map to %s", request.map_url.c_str());
Seems odd to tell the user we changed the map if the loadMapFromYaml failed? Should this message be moved into the if() statement only? (it looks like we already get error messages from the loadMapFromYaml function).

2021-05-19 12:32 UTC, engineeve commented
Any chance this will be merged within the next month?

2021-05-27 14:23 UTC, merged

2021-08-25 05:58 UTC, HappySamuel commented
Hi @DLu 

I saw that there's an addition feature (change_map) to the map_server. Is this add-on feature available if install via apt? 
`$ sudo apt install ros-noetic-map-server`
Because i check wiki of [ros noetic map server](http://wiki.ros.org/map_server), it remains outdated.

Best,
Samuel

2021-10-07 21:04 UTC, DLu commented
No, and its been over a year since the last release, so its overdue.