Fix Costmap2D future robot pose with static_transform_publisher
ros-planning/navigation pull request #1049
Opened 2020-11-12 17:31 UTC by pavloblindnology

Fixes #1048

2020-11-27 14:22 UTC, mikeferguson requested changes
This looks good - logic checks out. Can you update the style issues and retarget this to Noetic-devel (I will cherry-pick to back port to melodic)

2020-11-27 14:22 UTC, mikeferguson commented on costmap_2d/src/costmap_2d_ros.cpp
> +    if (tf_.canTransform(global_frame_, robot_base_frame_, current_time)) {
I know styling is inconsistent through navigation repo - but let's keep this file as consistent as possible, please move the opening brace to the it's own line.

2020-11-27 14:22 UTC, mikeferguson commented on costmap_2d/src/costmap_2d_ros.cpp
> +    else {
Same - new line for the brace

2020-12-08 17:39 UTC, pavloblindnology commented on costmap_2d/src/costmap_2d_ros.cpp
> +    else {
Done

2020-12-08 17:41 UTC, closed without merging

2021-05-19 09:00 UTC, pavloblindnology commented
@mikeferguson Can you please cherry pick this to melodic?