move_base crash when using default recovery behaviors
ros-planning/navigation pull request #1071
Opened 2020-12-19 18:36 UTC by mattp256

It looks like the recent update to publish recovery behavior leaves the recovery_behavior_names_ vector uninitialized if no recoveries are listed in configuration (i.e. using defaults). This caused move_base to crash during recovery on my setup, when trying to access the names vector to publish. Commit  b7379f7 is proposed to fix this.

Also, I thought the published info made more sense if it was 1-based instead of 0-based (e.g. "Executing behavior 1 of 2"). Commit d6ae66f is a proposal for that, but the crash fix can just be cherry-picked if this shouldn't change.

2020-12-20 01:14 UTC, mikeferguson approved these changes

2020-12-20 01:14 UTC, mikeferguson commented
LGTM - @DLu you actually authored the changes that this references - can you double check it? I think we also need to back port to Melodic (Kinetic has not been merged yet)

2020-12-29 00:44 UTC, DLu requested changes
Apologies for the bug. 

As for the indexing, the [message definition](https://github.com/ros-planning/navigation_msgs/blob/793d06ff51d20fcd94832161ccde268cb4ce5e38/move_base_msgs/msg/RecoveryStatus.msg#L2) denotes it as a 0-based index. I am ambivalent about keeping the +1 on the ROS_DEBUG but the current_recovery_number should stay as is.

2020-12-29 21:52 UTC, mikeferguson commented
CI was passing prior to build farm upgrades, the added commit should be fine (just removing a +1), going to merge so we can cherry pick and close out this bug

2020-12-29 21:52 UTC, merged

2020-12-29 21:54 UTC, mikeferguson commented
Cherry picked to melodic