use boost::placeholders::_N instead of deprecated _N
ros-planning/navigation pull request #1198
Opened 2022-05-16 15:37 UTC by lucasw

This eliminates a warning message about _1/_2 etc. and boost/bind.hpp being deprecated encountered building this on Ubuntu 22.04 (and from similar changes in other repos probably Arch and Gentoo see them also).

I also had to change to C++17 to avoid std::share_mutex log4cxx build errors- but could separate that out if necessary

    /usr/include/log4cxx/boost-std-configuration.h:10:18: error: ‘shared_mutex’ in namespace ‘std’ does not name a type

2022-06-20 18:00 UTC, mikeferguson requested changes

2022-06-20 18:00 UTC, mikeferguson commented on amcl/CMakeLists.txt
> +  set(CMAKE_CXX_STANDARD 17)
the recommended C++ for Noetic is 14 - I don't think we want to change this to be 17 - can the rest of these changes be done without changing the version?

2022-06-30 18:53 UTC, lucasw commented on amcl/CMakeLists.txt
> +  set(CMAKE_CXX_STANDARD 17)
If I delete that line entirely it will default to 14 on Ubuntu 20.04 and 17 on Ubuntu 22.04- would that be preferable?

2022-06-30 18:56 UTC, mikeferguson commented on amcl/CMakeLists.txt
> +  set(CMAKE_CXX_STANDARD 17)
Yeah, I think that is probably the correct thing to do here

2023-04-01 13:48 UTC, lucasw commented
The boost bind change was later done differently with lambdas in https://github.com/ros-planning/navigation/pull/1225/commits/80bf439cf98b0da5deb7c6d38075f8d112fc03ca, c++ version in https://github.com/ros-planning/navigation/pull/1225/commits/977c955393f6ba151362eb67e841c14e91f72da9 and merged in https://github.com/ros-planning/navigation/pull/1225

2023-04-01 13:48 UTC, closed without merging