Fix for #517: create a getRobotPose method on move_base
ros-planning/navigation pull request #520
Opened 2016-09-22 11:04 UTC by corot

instead of using that on the costmaps.

Solves (I would say surprisingly) the 
```
"Unable to get starting pose of robot, unable to create global plan"
```
problem.

 Change is very simple and hardly harmful. But I cannot tell what is exactly fixing nor why...

2017-08-01 18:00 UTC, mikeferguson requested changes
I like this PR -- but I don't like the breaking of ABI in the Costmap2dROS class (which will cause all sorts of hell on people with out-of-sync plugins, which is tough to track down). Here's my proposal:

 * I will cherry-pick this as-is into Lunar. There are far fewer users and we've still been fixing build issues over there, so stability should not yet be expected.

 * We update this PR to hard-code name+tolerance as parameters to MoveBase::getRobotPose() since ABI of MoveBase class does not matter.

 * Once we merge this updated version into indigo, I will cherry-pick to Kinetic

2017-08-01 18:00 UTC, mikeferguson commented on move_base/src/move_base.cpp
> +  bool MoveBase::getRobotPose(tf::Stamped<tf::Pose>& global_pose, costmap_2d::Costmap2DROS* costmap)
ABI in MoveBase doesn't matter, for Indigo+Kinetic -- let's add the name & transform_tolerance to this function signature, and then hard code them above (not great, but avoids ABI break). For Lunar -- let's go ahead and put this PR just this way (with the Costmap2DROS ABI change)

2017-08-02 08:41 UTC, corot commented on move_base/src/move_base.cpp
> +  bool MoveBase::getRobotPose(tf::Stamped<tf::Pose>& global_pose, costmap_2d::Costmap2DROS* costmap)
:+1:

2017-08-04 08:11 UTC, corot commented on move_base/src/move_base.cpp
> +  bool MoveBase::getRobotPose(tf::Stamped<tf::Pose>& global_pose, costmap_2d::Costmap2DROS* costmap)
btw @mikeferguson, do you want me to apply the requested changes? Or will you do by yourself?

2020-07-03 15:02 UTC, DLu commented
This was merged into lunar in #601 and is a part of melodic and noetic as well.

2020-07-03 15:02 UTC, closed without merging