Make sure to call setFootprint() before an in-place rotation
ros-planning/navigation pull request #681
Opened 2018-03-15 22:18 UTC by gerkey

This PR should fix #327, which we ran into on a project recently. I'm sure that there are a variety of ways to address the issue, but this set of changes seems to me the least intrusive way to ensure that `setFootprint()` is called before what might be an in-place rotation without any prior translation.

2018-03-16 18:53 UTC, mikeferguson commented
Seems reasonable to me -- I'm going to leave it for a day or two so @DLu can possibly comment since I think he is more familiar with these local planners.

2018-03-16 18:59 UTC, gerkey commented
Hmm, now that I've looked at the code again, I should probably make `footprint_spec` a const reference when passed into `updatePlanAndLocalCosts()`. If you guys think that this overall approach makes sense, then I'll also make and test that change.

2018-03-19 15:18 UTC, pavloblindnology commented
Why not to remove footprint setting from `DWAPlanner::findBestPath` additionally? It's not needed anymore after your changes.
https://github.com/ros-planning/navigation/blob/956c2c9e6fddce5484343cfc97dbc4e7217edcc2/dwa_local_planner/src/dwa_planner.cpp#L295

2018-03-20 17:22 UTC, DLu requested changes
I concur with the two points made thus far.
 * Should be a const ref
 * The footprint is not needed in findBestPath

I've made these changes in [a branch here](https://github.com/gerkey/navigation/compare/set_footprint_before_in_place_rotation...DLu:set_footprint_before_rotation?expand=1) that you can merge in if you'd like.

2018-04-11 17:40 UTC, enwpoa332 commented
Not sure if this solves the problem. 

In `DWAPlannerROS::computeVelocityCommands()`, if the first nav goal is on top of `current_pose_`, then `latchedStopRotateController_.isPositionReached()` returns `true`, and `DWAPlanner::checkTrajectory()` is called. This leads to `ObstacleCostFunction::scoreTrajectory()`, which depends on `ObstacleCostFunction::setFootprint()` having set the `ObstacleCostFunction::footprint_spec_` member. With a const reference instead of the `setFootprint()`, the `footprint_spec_.size()` will still return zero.

2019-02-11 19:17 UTC, DLu commented
Closed in favor of #829

2019-02-11 19:17 UTC, closed without merging