global_planner: enable default_tolerance with potential field, fix #262
ros-planning/navigation pull request #703
Opened 2018-03-29 14:04 UTC by nlimpert

Previously the default_tolerance parameter was not used leading to
failure when the desired goal was inside an obstacle.
In case the goal is inside an obstacle the global_planner now tries to
find a cell with pot_field_max_cost as its maximum value as close as
possible around the desired goal pose. This is achieved by calculating a
potential field in the area of the desired goal pose.
This area is defined by the default_tolerance parameter.

@mikeferguson this should fix #262.
See a demonstration video at https://fh-aachen.sciebo.de/s/i4GLL1pwUrpF1Jm

2018-03-29 19:54 UTC, DLu commented
There's quite a lot going on here, but shouldn't the logic be based on `tolerance` instead of `default_tolerance_`?

2018-03-30 09:09 UTC, nlimpert commented
Of course you are right - Thanks for the notice!

2018-06-11 19:26 UTC, mikeferguson commented
@DLu looks like you started to review this, it's another global_planner one if you have a chance.

2018-06-15 20:10 UTC, DLu requested changes
Thanks for this pull request. The fact that the tolerance was not used to begin with was an oversight on my part. 

There's a couple key stylistic things and extraneous bits of code that make this PR a little tricky. However, my main question is about how exactly you're picking the new goal location. At the very least, it could use some more comments about how that calculation is done. There's also [a nice-ish implementation in `move_base`](https://github.com/ros-planning/navigation/blob/melodic-devel/move_base/src/move_base.cpp#L376) that just searches with increasing distances, which is a little more straightforward.

2018-06-15 20:10 UTC, DLu commented on global_planner/include/global_planner/planner_core.h
> +        costmap_2d::Costmap2DROS* costmap_ros_;
It doesn't look like you use costmap_ros_ anywhere in this PR.

2018-06-15 20:10 UTC, DLu commented on global_planner/include/global_planner/planner_core.h
> +        std::vector<float> proj_modes;
Likewise, proj_modes is not used here either.

2018-06-15 20:10 UTC, DLu commented on global_planner/include/global_planner/planner_core.h
> +        double last_official_goal_y;
The standard style in this code is for member variables to end with an underscore.

2018-06-15 20:10 UTC, DLu commented on global_planner/include/global_planner/planner_core.h
> +        double new_goal_y;
Why did you make `new_goal_x` and `y` member variables and not just local variables?

2018-06-15 20:10 UTC, DLu commented on global_planner/src/planner_core.cpp
> +        private_nh.param("pot_field_min_", publish_scale_, 100);
A) parameter names should not end with an underscore.
B) It probably shouldn't be setting publish_scale, but I'm not sure what its supposed to set either.

2018-06-15 20:10 UTC, DLu commented on global_planner/src/planner_core.cpp
> +    }
If `initialize` is not called, then `last_official_goal_x` will not be initialized, so either, you should
 * Move the initialization to the constructor's initializers (preferred)
 * or Move this if statement to after the initialized check on the next line.

2018-06-15 20:10 UTC, DLu commented on global_planner/src/planner_core.cpp
> +    geometry_msgs::PoseStamped goal_ = goal;
Likewise, local variables like `goal_` should NOT end in underscores.

2018-06-15 20:10 UTC, DLu commented on global_planner/include/global_planner/planner_core.h
> +#define POT_FIELD_TIMEOUT 1.0  // Timeout of potential field method
This should probably be a ROS parameter instead of a `#define`

2018-06-15 20:10 UTC, DLu commented on global_planner/src/planner_core.cpp
> +        float cur_y = std::sin(pot_field_target_phi) * (costmap_->getResolution() * 0.5);
Can you explain what this math is doing, please?

2019-03-11 08:25 UTC, nlimpert commented
I'm sorry for the super-late response!
I agree that there are major flaws in this PR and I also agree that the solution implemented in `move_base` is much more elegant.

So I currently tend to re-implement this based on the [solution](https://github.com/ros-planning/navigation/blob/b52e0ea9362131dc81326da471792ab8698c9564/move_base/src/move_base.cpp#L376) in `move_base` that @DLu pointed at.

However seeing this makes me wonder why this would need to be implemented in two different places.
But I guess it's better to have a working `default_tolerance` parameter even though the feature is already available in `move_base` (while it doesn't seem to be usable without `move_base`'s `planService`).

I think this would look completely different than the current PR. Would you like me to create a new PR or simply update this one?

2020-03-13 14:26 UTC, nlimpert commented
Closing this as it will be targeting melodic and it needs a proper rework of the proposed feature.

I'll open a new PR once I'm ready.

2020-03-13 14:26 UTC, closed without merging