Adding service to set custom particles
ros-planning/navigation pull request #753
Opened 2018-07-11 21:59 UTC by vik748

This commit adds a service called "amcl/set_particles" to the amcl node to accept a Pose array of particles to set custom particles in AMCL.

2018-07-18 05:30 UTC, mikeferguson requested changes
A couple of style issues noted.

A separate issue: it is a little late to add such a new feature to Kinetic. Also, we can't just cherry pick this into Melodic (since it has been converted to use TF2). If possibly, I'd really prefer we update this to use TF2 and merge it into Melodic only. Thoughts?

2018-07-18 05:30 UTC, mikeferguson commented on amcl/src/amcl_node.cpp
> +	{
indentation is off here -- looks like you've got some tabs -- indent should 2 spaces

2018-07-18 05:30 UTC, mikeferguson commented on amcl/src/amcl_node.cpp
> +  ROS_INFO("Received set particles srv call, Pose Array Header stamp = %0.4f",req.pose_array_msg.header.stamp.toSec());
All this output feels a little spammy (7 ROS_INFOs per call). I'd suggest converting all but one of them to ROS_DEBUG_NAMED() calls -- with a good namespace so it's easy to turn on.

2018-07-18 05:30 UTC, mikeferguson commented on amcl/src/amcl_node.cpp
> +  //std::cout<<"Size of array "<<parray->poses.size()<<std::endl;
please convert to ROS_DEBUG_NAMED, or remove

2018-07-19 01:38 UTC, shahvi commented
@mikeferguson I have updated the node to address your formatting comments.  As for whether to include it into Kinetic, I'll let you decide the norm.  I just wanted to leave this here so that anyone interested could have access to it.
As for the update for Melodic, I haven't really installed / used Melodic yet.  So I won't get around to updating this to TF2 anytime soon.
Just to understand the process, if / when I get to committing those changes in Melodic.  Do I just update the melodic branch in my fork or would that be a completely new pull request?

2022-06-20 18:22 UTC, mikeferguson commented
Targets a dead release (kinetic). If this is still of interest, please open a PR to noetic-devel branch

2022-06-20 18:22 UTC, closed without merging