Implement the new move base flex interface for the global planner
ros-planning/navigation pull request #774
Opened 2018-07-31 07:53 UTC by vsteinb

Added a second inheritance to GlobalPlanner from the mbf_costmap_core::CostmapPlanner interface to be able to use move_base_flex while backwards compatible to move_base.

2018-07-31 13:09 UTC, mikeferguson commented
So, this really isn't going to work -- we can't depend on things from the MBF repo, since the MBF repo has packages that depend on at least costmap_2d, base_local_planner, and nav_core.

2018-08-01 13:49 UTC, spuetz commented
Aaa circular dependencies. :/ @corot How could we handle that?

2018-08-01 14:24 UTC, corot commented
I think build just fails because mbf_msgs dependency is missing; same for the local planner.

I don't see any circular dependency; true mbf_costmap_core depends on costmap_2d, but also does nav_core

2018-08-01 14:45 UTC, mikaelarguedas commented
I believe what @mikeferguson means is that the ROS release infrastructure works on a per repository basis.
So circular dependencies should not only be avoided at the package level but also at the repository level. And this PR will introduce a repository level circular dependency between `navigation` and `move_base_flex` that will prevent them from being released

2018-08-01 14:46 UTC, spuetz requested changes
There are some things to change. And some things also missing. mbf_msgs dependency, and cost is not computed or set and message is not set. The rest looks fine to me.

2018-08-01 14:46 UTC, spuetz commented on global_planner/src/planner_core.cpp
> +        return mbf_msgs::GetPathResult::INTERNAL_ERROR;
`INVALID_GOAL` would be the right outcome number code here.

2018-08-01 14:46 UTC, spuetz commented on global_planner/src/planner_core.cpp
> +        return mbf_msgs::GetPathResult::INTERNAL_ERROR;
`INVALID_START` would be the right number code here.

2018-08-01 14:46 UTC, spuetz commented on global_planner/src/planner_core.cpp
> +        ROS_ERROR("This planner was canceled!");
The error msg is a bit unspecific.

2018-08-01 14:46 UTC, spuetz commented on global_planner/src/planner_core.cpp
> +                  double tolerance, std::vector<geometry_msgs::PoseStamped> &plan, double &cost, std::string &/*message*/) {
- /*message*/ ? 
- where is the cost computed
- where is the message set? -> The message should be defined following to the error meaning.

2018-08-01 14:46 UTC, spuetz commented on global_planner/package.xml
mbf_msgs is missing here

2018-08-01 14:46 UTC, spuetz commented on global_planner/package.xml
>    <export>
mbf_msgs

2018-08-01 14:46 UTC, spuetz commented on global_planner/CMakeLists.txt
>      navfn
mbf_msgs is missing here

2018-08-02 01:56 UTC, mikeferguson commented
Yes, what @mikaelarguedas mentioned is the problem -- since we certainly want to release debians.

I think the proper way to get this out would be to include a minimal set of headers in nav_core (Ala this PR: https://github.com/ros-planning/navigation/pull/605). Since we haven't sync'd the first round of debians yet -- it is definitely still early enough to get this into Melodic.

Or split the core stuff out of move_base_flex into a new repo (but before I would support navigation depending on said code, I'd suggest that move_base_flex_core be part of ors-planning, so that if in the future you guys decide to stop maintaining it, we can still release it and the navigation stack).

2018-08-02 12:35 UTC, jspricke commented
I would propose to not change navigation and handle the extended plugins at runtime in mbf.

2018-08-02 13:01 UTC, corot commented
That's what we currently do; when dealing with "old-stile" API (nav_core) plugins, MBF wraps them so they can be used indistinctly from "new-stile" API (mbf_core) plugins. Problem is that we miss the richer interface, as nav_core plugins don't provide error code or message, just success/failure, nor can be canceled (plus other new fancy stuff).

2018-08-02 13:06 UTC, corot commented
So as I see, there are several possibilities (all for melodic and later, kinetic will just remain as it is):

- add mbf_core and mbf_msgs to ROS navigation repo, and upgrade the plugins to the new interface (backward compatible!). Main problem is the increased complexity (possibly confusing for newcomers) of ROS navigation stack
- move the plugins to a separated repo, so the can freely depend on both ROS nav (core, msgs, costmaps...) and MBF (mbf_core, mbf_msgs). Probably too much work for the maintainers.
- duplicate the plugins and re-release with a mbf_ prefix. Duplicate == :imp: 
- let things as they are and make a common interface (both C++ plugin and ROS API) for ROS 2.0 navigation.

2020-03-03 18:37 UTC, mikeferguson commented
Going to close this since we never resolved the circular dependency - and we certainly aren't going to make this change in Kinetic

2020-03-03 18:37 UTC, closed without merging