[global_planner] Do not clear the starting cell in the costmap
ros-planning/navigation pull request #896
Opened 2019-06-24 12:37 UTC by corot

I wonder what's the reason to do so. Planner seems to work just fine without it.

The reason I need to remove this is because sometimes I call SBPL lattice planner right after global_planner, and it creates paths that go into collision. The reason is that, because of this clearRobotCell method, the robot starts in a zero-cost cell, and SBPL assumes that no action can bring the robot into collision from here (as it assumes the closest obstacle is at at least at inflation_radius m away)

2019-06-25 02:33 UTC, DLu requested changes
This is my answer for a lot of things, but it is that way because [its always been that way](https://github.com/ros-planning/navigation/blob/melodic-devel/navfn/src/navfn_ros.cpp#L234). My impression is that certain robots would get sensor noise for the cell they were in, and this would enable them to succeed more often. 

Since this is disrupting your other workflow, I agree that this users should at least have the option to disable this. If you hide the behavior behind a param (defaulting to the current behavior) I'll merge it.

2019-06-25 09:23 UTC, corot commented
Or alternatively, I can just restore the costmap to its initial status, whatever you like the most.

2019-06-26 13:00 UTC, DLu commented
I think having a parameter to control whether you clear it or never touch it should sufficient.

2019-06-27 10:06 UTC, corot commented
Closed in favor of #897

2019-06-27 10:06 UTC, closed without merging