Add 'do_not_alter_costmap' parameter that forces planner to not change costmap
ros-planning/navigation pull request #897
Opened 2019-06-27 10:05 UTC by corot

More general version of PR #896, with the requested change of making the change not applicable by default. Instead of just removing the call to _clearRobotCell_, I offer now the option of not altering the costmap at all by copying its underlying char array and working only on it.

Another good thing of this approach is that we can choose (TODO in another PR) to lock the costmap only while copying it, so we allow updates during planning. This is useless on current move_base, but on [move_base_flex](https://github.com/magazino/move_base_flex) it's optional to lock the costmaps, delegating on the plugins to do so. This is a good thing for slow planners like sbpl that only invest a minimal time to copy the costmap at the beginning and then take very long while planning over his copy; on current move_base, all this time the costmap is frozen without any benefit.

2019-06-28 19:34 UTC, DLu requested changes

2019-06-28 19:34 UTC, DLu commented on global_planner/src/planner_core.cpp
> +        private_nh.param("do_not_alter_costmap", do_not_alter_costmap_, false);
I would prefer `plan_on_costmap_copy` to avoid the negation.

2019-06-28 19:34 UTC, DLu commented on global_planner/src/planner_core.cpp
> +        costmap_char_array = new unsigned char[nx * ny];
I would move this up to the parent class so you don't realloc every iteration.

2020-06-24 08:37 UTC, dorezyuk commented
Hey guys, what the state of this PR? I think the idea not to alter the costmap is very right, however, I'm not sure if copying of the costmap is really necessary. Could we just write

```
    if(clear_robot_pose_)
        clearRobotCell(start, start_x_i, start_y_i);
    else if(costmap_->getCost(start_x_i, start_y_i) >= costmap_2d::INSCRIBED_INFLATED_OBSTACLE) {
        ROS_WARN_THROTTLE(1.0, "The robot's start position is in collision");
        return false;
    }
```
with a `clear_robot_pose_` parameter defaulting to true?

2025-06-04 17:05 UTC, mikeferguson commented
ROS 1 is now EOL. Please consider migrating to https://github.com/ros-navigation/navigation2

2025-06-04 17:05 UTC, closed without merging